### ISSUE TITLE
Desain tampilan aplikasi

### ISSUE THREAD

**Issue by iqrev** [iqrev/todolist#18]
- [x] Link  Figma : https://www.figma.com/file/Ct2utCCRTHLM0sdEyHMRTn/Project-Pemograman-Visual-Kelompok-4?type=design&node-id=0%3A1&t=Qfabg6fwjOVL8je8-1

- [x] Tampilan Awal ( Log in, Sing Up, Halaman Depan ) : 
https://drive.google.com/drive/folders/13Z5oxRF_eDrCkM5cO0o-QcCGRvg5kT__?usp=sharing

- [x] Task
https://drive.google.com/drive/folders/166x8kWbQ6CT-nKqsn4V41QszbeuqcP_h?usp=sharing

- [x] Daily Task
https://drive.google.com/drive/folders/1dhLi6T2NnOwfChfN3SKCrce0oAUB7c_a?usp=sharing

- [x] Important
https://drive.google.com/drive/folders/1NSzp-waCMPfz8nR9dqqcu75dEzKuawsa?usp=sharing

- [x] Complete 
https://drive.google.com/drive/folders/1wjJfeEItaqpuqF06PGY4eUuml-U-JwB2?usp=sharing

**Comment by Srisulistina** [comment]
Halaman depan : Halaman depan derisikan Sign Up dan Sing In

1. Fitur Daily Task : digunakan untuk membantu seseorang mengatur dan mengelola kegiatan sehari harinya seperti waktu olahraga, makan, tidur dan lain lain 

2. Fitur Important : digunakan untuk memfilter tugas atau kegiatan yang penting untuk di selesaikan terlebih dahulu 

3. Fitur Task : digunakan untuk membuat 

4. Fitur Complate : untuk menyimpan semua kegiatan yang telah selesai dilakukan 

7. Fitur Manage Categories : digunakan untuk megatur dan menambah kategori yang akan di gunakan pada setiap taks yang akan dibuat sesuai kebutuhan dari pengguna.

8. Fitur Next Step : pada setiap taks yang dibuat pengguna dapat membuat langkah langkah yang akan di lakukan. 

9. Fitur Remainder :  membantu pengguna untuk mengingat hal-hal penting yang perlu dilakukan atau diperhatikan pada waktu tertentu.

10. Fitur Start : digunakan pengguna untuk mengatur waktu akan untuk melakukan kegiatan atau tugas yang telah dibuat pada fitur taks. 

11. Fitur End : digunakan pengguna untuk megatur tenggat waktu dalam melakukan kegitan atau tugas yang telah dibuat pada fitur taks

15. Fitur Categories : digunkan pengguna untuk mengatur kategori dalam taks yang dibuat sehingga taks akan lebih rapi dan teratur.

**Comment by iqrev** [comment]
di figma halamannya jadiin frame jangan jadiin grup, atur komposisi teksny biar rata dan tidak berantakan

**Comment by Srisulistina** [comment]
Okey silahkan dicek pada figma di page 3 : https://www.figma.com/file/RFLK3lQlrFcInDJl5sY9x6/TODO-LIST?type=design&node-id=20%3A249&t=Cx20cSnbzarAv7vv-1
