### ISSUE TITLE
Metode pengembangan aplikasi

### ISSUE THREAD

**Issue by Dwiurfathulfitria** [iqrev/todolist#2]
Tugas: mendefinisikan metode agile serta gambar.

**Comment by cahyasyalom** [comment]
Metode agile adalah metode pengembangan perangkat lunak yang dilakukan secara berulang pada proses pengerjaannya yang terdiri dari aturan dan solusi yang telah disepakati. Metode ini sangat cocok untuk proyek jangka pendek dikarenakan metode ini akan sangat mudah beradaptasi apabila terjadi perubahan dalam suatu proyek.
